# Main build jobs for CI/CD on Azure Pipelines.

parameters:
- name: builds
  type: object
  default:

  - name: linux_stable
    vmImage: ubuntu-20.04
    vars:
      TARGET: x86_64-unknown-linux-gnu
      TOOLCHAIN: stable

  - name: linux_beta
    vmImage: ubuntu-20.04
    vars:
      TARGET: x86_64-unknown-linux-gnu
      TOOLCHAIN: beta

  - name: macos
    vmImage: macos-latest
    vars:
      TARGET: x86_64-apple-darwin
      TOOLCHAIN: stable

jobs:
- ${{ each build in parameters.builds }}:
  - job: ${{ format('build_{0}', build.name) }}
    pool:
      vmImage: ${{ build.vmImage }}
    steps:

    - template: azure-job-setup.yml
      parameters:
        setupBuild: true

    - bash: cargo build --all --release
      displayName: "cargo build (release)"

    - bash: cargo build --all --release --examples
      displayName: "cargo build examples (release)"

    - bash: cargo test --all --release
      displayName: "cargo test (release)"

    variables:
      ${{ insert }}: ${{ build.vars }}
